Spring:
    #配置数据源
    datasource:
        name: car_manage_system
        url: jdbc:mysql://116.63.170.243:3306/car_manage_system #url
        username: root  #用户名
        password: TangHuoGuo1@3  #密码
        driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动

mybatis:
    mapper-locations: classpath:mapper/*.xml  #配置映射文件
    type-aliases-package: com.example.bean #配置实体类

fdfs:
    pool:
        max-total: 200 # 连接池最大数量
        max-total-per-key: 50  # 每个tracker地址的最大连接数
        max-wait-millis: 5000  # 连接耗尽时等待获取连接的最大毫秒数
    so-timeout: 1501 #上传的超时时间
    connect-timeout: 601 #连接超时时间
    thumb-image:             #缩略图生成参数
        width: 150
        height: 150
    tracker-list:            #TrackerList参数,支持多个
        - 192.168.2.201:22122
        - 192.168.2.202:22122

server:
    port: 9091
#    address: 116.63.170.243

#配置dubbo信息
dubbo:
    application:
        name: picture-service-provider
    registry:
        #注册中心地址
        #制定超时时间,单位毫秒
        timeout: 5000
        address: zookeeper://192.168.2.31:2181?backup=192.168.2.32:2181,192.168.2.33:2181 #zookeeper集群
        #配置元数据中心 --> 用于存储服务的元数据,消费者在消费服务的时候只需要注册中心提供某个服务的关键数据即可,
        #将服务本身必须要但是消费者不需要的数据存放到元数据中心,这样可以提供性能和服务调度的效率
        simplified: true #注册到注册中心的URL是否采用精简模式的 （与低版本兼容）
    metadata-report:
        address: zookeeper://192.168.2.31:2181?backup=192.168.2.32:2181,192.168.2.33:2181
    #协议
    protocol:
        name: dubbo
        port: 20881
    #制定扫描的基础包
    scan:
        base-packages: com.example.serviceImpl
    provider:
        timeout: 50000


#配置springboot热部署
spring:
    devtools:
        restart:
            enabled: true
            #设置重启目录
            additional-paths: src/main/java
            exclude: WEB-INF/**
    freemarker:
        cache: false #页面不加载缓存,修改及时生效